repos:
    - repo: local
      hooks:
          - id: poetry-check
            name: poetry-check
            entry: poetry check
            language: system
            pass_filenames: false

          - id: poetry-lock
            name: poetry-lock
            entry: poetry lock
            language: system
            pass_filenames: false
            args: ["--no-update"]

          - id: poetry-export
            name: poetry-export
            entry: poetry export
            language: system
            pass_filenames: false
            args:
                [
                    "-f",
                    "requirements.txt",
                    "-o",
                    "requirements.txt",
                    "--without-hashes",
                ]

          - id: black
            name: black
            entry: poetry run black
            language: system
            types: [python]

          - id: flake8
            name: flake8
            entry: poetry run flake8
            language: system
            types: [python]
            exclude: migrations/
