# Generated by Django 5.1 on 2024-09-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="url",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
